#!/usr/bin/env php
<?php
    require __DIR__ . '/../../../../vendor/autoload.php';

    use Platine\Framework\App\Application;
    use Platine\Framework\Kernel\ConsoleKernel;

    $app = new Application();
    $app->setConfigPath(__DIR__ . '/../../../../packages/app/config');

    $kernel = $app->make(ConsoleKernel::class); 

    $kernel->run($_SERVER['argv'] ?? []);

